package com.qrcode.backend.dao;

import com.qrcode.backend.model.QrCode;
import com.qrcode.backend.util.DatabaseConnection;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Data Access Object for the {@code qr_codes} table.
 *
 * <p>Every method manages its own {@link Connection} via
 * {@link DatabaseConnection#getConnection()} and closes it
 * in a try-with-resources block.</p>
 */
public class QrCodeDao {

    private static final Logger LOGGER = Logger.getLogger(QrCodeDao.class.getName());

    // ------------------------------------------------------------------
    // Write operations
    // ------------------------------------------------------------------

    /**
     * Inserts a new QR code record into the database.
     *
     * @param userId      the ID of the user who generated it
     * @param content     the original text / URL that was encoded
     * @param imageBase64 the Base64-encoded PNG image string
     * @return the auto-generated record ID, or -1 on failure
     */
    public static int save(int userId, String content, String imageBase64) {
        String sql = "INSERT INTO qr_codes (user_id, content, image_base64) VALUES (?, ?, ?)";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setInt(1, userId);
            stmt.setString(2, content);
            stmt.setString(3, imageBase64);
            stmt.executeUpdate();

            try (ResultSet keys = stmt.getGeneratedKeys()) {
                if (keys.next()) {
                    int newId = keys.getInt(1);
                    LOGGER.info("QR code saved: id=" + newId + " userId=" + userId);
                    return newId;
                }
            }

        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Failed to save QR code: " + e.getMessage(), e);
        }

        return -1;
    }

    /**
     * Deletes a QR code record by ID, but only if it belongs to the given user.
     * Returns true if a row was deleted.
     */
    public static boolean deleteByIdAndUserId(int id, int userId) {
        String sql = "DELETE FROM qr_codes WHERE id = ? AND user_id = ?";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, id);
            stmt.setInt(2, userId);
            int affected = stmt.executeUpdate();
            return affected > 0;

        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Failed to delete QR code id=" + id, e);
        }

        return false;
    }

    // ------------------------------------------------------------------
    // Read operations
    // ------------------------------------------------------------------

    /**
     * Finds a single QR code by its ID.
     */
    public static Optional<QrCode> findById(int id) {
        String sql = "SELECT id, user_id, content, image_base64, created_at "
                + "FROM qr_codes WHERE id = ?";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, id);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) return Optional.of(mapRow(rs));
            }

        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Failed to find QR code id=" + id, e);
        }

        return Optional.empty();
    }

    /**
     * Returns all QR codes belonging to a specific user,
     * ordered newest-first.
     *
     * @param userId the user's ID
     * @return list of QR code records (may be empty, never null)
     */
    public static List<QrCode> findByUserId(int userId) {
        String sql = "SELECT id, user_id, content, image_base64, created_at "
                + "FROM qr_codes WHERE user_id = ? ORDER BY created_at DESC";

        List<QrCode> results = new ArrayList<>();

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, userId);

            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) results.add(mapRow(rs));
            }

        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Failed to list QR codes for userId=" + userId, e);
        }

        return results;
    }

    /**
     * Returns the total number of QR codes generated by a user.
     */
    public static int countByUserId(int userId) {
        String sql = "SELECT COUNT(*) FROM qr_codes WHERE user_id = ?";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, userId);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) return rs.getInt(1);
            }

        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Failed to count QR codes for userId=" + userId, e);
        }

        return 0;
    }

    // ------------------------------------------------------------------
    // Private helpers
    // ------------------------------------------------------------------

    private static QrCode mapRow(ResultSet rs) throws SQLException {
        QrCode qr = new QrCode();
        qr.setId(rs.getInt("id"));
        qr.setUserId(rs.getInt("user_id"));
        qr.setContent(rs.getString("content"));
        qr.setImageBase64(rs.getString("image_base64"));
        qr.setCreatedAt(rs.getTimestamp("created_at"));
        return qr;
    }
}
